### ISSUE TITLE
SPARQL endpoint does not function

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2047]
No SPARQL search is possible, meaning also that the Gender page https://betamasaheft.eu/gender is not working.
I am not sure I have the time and energy to fix it so I would hide the Gender button here
![image](https://user-images.githubusercontent.com/17987728/159905910-27a9b211-588b-4167-9415-7d782fc88bf5.png)
LitFlow also does not work but maybe I can fix it, if not then I would take that one out too. They can be re-inserted once the past functionality is back in place.

**Comment by PietroLiuzzo** [comment]
The SPARQL API and endpoint, as well as the triplestore do work. There seems however not to be sufficient data stored there.

**Comment by eu-genia** [comment]
then as I assumed this must be related to
https://github.com/BetaMasaheft/Documentation/issues/1972

**Comment by PietroLiuzzo** [comment]
I have checked the RDF data and there is a problem caused by the data2rdf.xslt which concatenates things of this kind 
https://betamasaheft.eu/https://betamasaheft.eu/PRS6064Krapf

I have identified the offending places and fixed the XSLT. 

I am now setting up an environment to rebuild the RDF data and newly upload it. 
This will take sometime and perhaps you prefer to do it yourself instead? 

It should be sufficient to
- transform all files with the XSLT, saving the results to a local directory (will take a while)
- check the results
- set the nginx configuration to accept large uploads (uncomment value already available)
- upload to fuseki the transformed data in groups from the fuseki user interface
- test the queries
- comment the nginx config again.

The new data will replace the old.

The other issue may be solved similarly by replacing the current files in there and updating the switch to park the non matching files to another directory. This will remediate the broken rdf alternate links. This is again easy but time consuming. Let me know if you want me to do that or you can do it.

**Comment by eu-genia** [comment]
It is perfectly fine if you can do it, thank you!

**Comment by eu-genia** [comment]
(sorry, just for information: the switch to update, so that the RDFs are sorted where they belong - which one is that?)

**Comment by PietroLiuzzo** [comment]
ok, I am now checking also other issues and will keep this last to optimize time.

**Comment by PietroLiuzzo** [comment]
gender should work now and all data is being currently updated (mss and persons are done, rest follows as needed)

**Comment by PietroLiuzzo** [comment]
the literature sankey chart also has issues with range indexes.... I added a s missing at line 78 of LitFlowRest.xqm

**Comment by PietroLiuzzo** [comment]
The RDF data in fuseki has been cleared of the above errors running the following query from a separate instance.

````xquery
xquery version "3.1";

import module namespace fusekisparql = 'https://www.betamasaheft.uni-hamburg.de/BetMas/sparqlfuseki'at "xmldb:exist:///db/apps/BetMas/fuseki/fuseki.xqm";
import module namespace config = "https://www.betamasaheft.uni-hamburg.de/BetMas/config" at "xmldb:exist:///db/apps/BetMas/modules/config.xqm";

let $dataset := 'betamasaheft'
let $operation := 'DELETE'
let $triples := '?sub ?pred ?obj'
let $selector := "?sub ?pred ?obj .
     FILTER(STRSTARTS(STR(?obj), 'https://betamasaheft.eu/https://betamasaheft.eu/')) "
return
 fusekisparql:editSelection($dataset, $operation, $triples,  $selector)
````

the function called there is the following

````xquery
declare function fusekisparql:editSelection($dataset, $InsertOrDelete, $triples, $selector) {
    let $url := $fusekisparql:port||$dataset||'/update'
    let $sparqlupdate := $config:sparqlPrefixes || $InsertOrDelete || '
{ 
  '||$triples||'
} WHERE { ' || $selector || '}'
    let $req :=
    <http:request
        http-version="1.1"
        href="{xs:anyURI($url)}"
        method="POST">
        <http:header
            name="Content-type"
            value="application/sparql-update"></http:header>
        <http:body
            media-type="text/plain">{$sparqlupdate}</http:body>
    </http:request>
    let $post := http:send-request($req)[2]
    return
        $post
};
````

expanded data has been downloaded in end of June and now entirely retransformed. collection.xconf applied to expanded, and data imported in exist-db 6.0.1 instance, then run following

````xquery
for $file in $context
let $start-time := util:system-time()
let $rdf := try{transform:transform($file, $local:data2rdf, ())} catch * {util:log('info', $file),util:log('info', $err:description)}
 let $updateFuseki := try{updatefuseki:update($rdf, 'INSERT')} catch * {$err:description}
let $runtime-ms := ((util:system-time() - $start-time) div xs:dayTimeDuration('PT1S'))
return
'stored RDF/XML and updated fuseki in ' || $runtime-ms 
````
on each collection with corrected version of data2rdf.xslt. run on local exist-db 6.0.1 instance as well, tested storing to apache jena fuseki 4.5 then used to store data to bm apache fuseki instance (4.3)

**Comment by eu-genia** [comment]
Just going through: I still get the same error in LitFlow (I do see the keywords)
Is it me who is doing something wrong?
***@***.***

Von: Pietro Liuzzo ***@***.***
Gesendet: Freitag, 12. August 2022 22:03
An: BetaMasaheft/Documentation ***@***.***>
Cc: Sokolinski, Eugenia ***@***.***>; Author ***@***.***>
Betreff: Re: [BetaMasaheft/Documentation] SPARQL endpoint does not function (Issue #2047)


the literature sankey chart also has issues with range indexes.... I added a s missing at line 78 of LitFlowRest.xqm

**Comment by PietroLiuzzo** [comment]
as reported, this is likely to have something to do with the indexes. As you read in the error it is the $field parameter of the range indexes function which is getting nothing.

**Comment by eu-genia** [comment]
gender gives few results, just 4 women, some data must be missing again... it used to be more
https://github.com/BetaMasaheft/Documentation/issues/1450

i did repopulate the rdf folders in the app as suggested https://github.com/BetaMasaheft/Documentation/issues/1972

**Comment by eu-genia** [comment]
the transformation was wrong, all rdfs had gender male. xslt corrected, persons reuploaded to fuseki. now the women are 81 (and 1071 male)

the loading times for sparql are very slow, it works faster from the endpoint at https://betamasaheft.eu/fuseki/dataset.html

**Comment by eu-genia** [comment]
visualization of sparql results with with d3sparql is not working

also graphs etc for gender are not working

**Comment by eu-genia** [comment]
rdf files are not produced automatically 
fuseki bm database is not being updated since the new release (except for dillmann, dillmann works ok)
![image](https://github.com/BetaMasaheft/Documentation/assets/17987728/ca3b9f54-44b3-4490-a8fd-cf5fb27214ca)

dillmann
![image](https://github.com/BetaMasaheft/Documentation/assets/17987728/53163dc4-f6eb-4ac7-9217-dc526e73b6ac)

bm
![image](https://github.com/BetaMasaheft/Documentation/assets/17987728/16478cf3-b23a-4352-8a7c-bc9614763d0f)
